[development]
dynaconf_merge = true

[development.security]
# openssl rand -hex 32
SECRET_KEY = "ONLYFORDEVELOPMENT"
#PRIVATE_KEY_ID = "bfc397ebc8e486181ac57b4737afc6900222fdb1"
#PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6Msm9JNGqO0Bb\ni25Eq30j8nZTlJBMeZ/RuwE8fLxX9lheYIORFaXD15iSYdBk0ejBPEoiHv6cw6VG\nulBLpFJPDIH5UXSZZwo//3xE+87WGVLa6py1WnyLD9lKRyw9FOdv/q27t5FYAJ63\nBegqkLsVDA+pc+koZGY1rt5v+31VANVOCIJenXewkuPOENRl1hpU+3H5gOGtMll3\nkwz371PSgvVgtZuuG9flTVYNu6R1J6gMRvxhVKcEuVYYXb9efirhERvztLeghmQ6\n70sLam7z/KnoGT2zbCorPVvFmr9xGEGwE/8BcptNrB3NRub1fqWVeBcdsbdsFrW7\npd5ADKzzAgMBAAECggEAE8m0+IsdVcbhPTlcA86TyIpfz9xwhL1s4i2ftoLCbg4J\n8HxiTxIVYUhGzdEOWWtDc1HJxnGJI+DY7jjRCBDpBxSbCtjWGD1um0Q2u+APkwpI\nQhKqingY10XdFPtBCibFZ84RlEBbIRaZHMtIaUmjUDEiyE0/YKG23l/8rLr15Alj\n1H1IbCSGM/kWiR4PjigaA8Qdqdx1THaFFsXMD4ulw9tJEg5HDJB0UbzF6/JYPWNZ\nMwzvUT2VaVcRUe1BqySacB//DEBh8jOCQG2/HZrZXJ966smlmlV9FBR2AuEtkyG9\naW7emUBM9VMtB1xv0T7ovJQ4WpLQ6t90w/EzVjug4QKBgQD/GtbxXzIt9lfLXvlC\nhOhS1K+UiOD5hcnQKrnxRx0MzBM+d37Si64p8O/Dwfzvl1jU1XRia4KDIWWYhGaU\n2Tpmk9GiYJk8CB6zwc5sgMytYuYgygz63yEphc9QGikQCAMw9CeUMJFUR4YXMno3\nZT4xEY170BIYpb/6qbPbT3ieIQKBgQC62gzCJ9WZMCbsEvWbY/VgGVHCxKNxGpfg\nUlwLq7w7ErkrB4AfWgi9RMc+2Gm2pYyqwWs2Hj5y2ukl7C7zw4m0XA6TqyFIcjeV\nX7xzNom5q91RMgXAzJhobj05WeM7iBrocWu7qBDpaGSCqUbOtSJiGEWOUUlovhRW\nijGzE83gkwKBgCuaqNbFEMyuaL9IUo6+LP/Lft+CrgG4jpBYXUQShbKkRz3MKw9N\n9M0Sc8kgJV3GntZyTdxsx/gmAzmYl/glUUgrSA/bNxX9xVGwdNozAck5OGCuaJ2Q\n+hgg2Ri2AALPe8woT4OS8aRYPWFFrYI+eezlNSvOmuk/m5r62tVHtjRBAoGABSv/\n6mfb26+fhC1KKxDrO8u3naJ/u6O2zHi7H3+TaDcudOhyPWvqjgKXWT/4PRv79sX/\nx7GynM8+YNRWwFyLNTjPFntIIo82xqWtu6qoyUDekV7HFf0TwuA6RZodVgqAZCqv\nhrQyM6O2FH/G+/W7i+eMFVJeq82HFpYgpgpISo0CgYBY2yrF7oQAc3AAjCZOYIEH\naqDx1hCmYePgjOfzxMyNw6ccZSE0sD7DcRnFs2BBLkRGiEPmZoU8quneNBVCtTUi\nENjTAHizWamYa27m+racnrl+GF1xv3/lCKzh4u3/NEycnuVbDJQL8cG9v7m+kIrW\ndr3kqTMy+xFn4jUFTglnTw==\n-----END PRIVATE KEY-----\n"

[production]
dynaconf_merge = true

[production.security]
SECRET_KEY = "@vault path/to/vault/secret"

[testing]
dynaconf_merge = true

[testing.security]
SECRET_KEY = "ONLYFORTESTING"