version: '3.9'

services:
  streamlit-app:
    container_name: myapp
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./:/app/
    networks:
      - chicago-crime-dev-case_chicago-crime
    depends_on:
      - app
  app:
    container_name: myapi
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - chicago_crime_dev_case_DB__uri=postgresql://postgres:postgres@db:5432/chicago_crime_dev_case
      - chicago_crime_dev_case_DB__connect_args={}
    volumes:
      - .:/home/app/web
    networks:
      - chicago-crime-dev-case_chicago-crime
    depends_on:
      - db
  db:
    build: postgres
    image: chicago_crime_dev_case_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/chicago_crime_dev_case_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=chicago_crime_dev_case, chicago_crime_dev_case_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  chicago-crime-dev-case_chicago-crime:
  
